// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIIrB63lyET_Mkl_3KTvcV6j1TeO_W_2w',
    appId: '1:861165103786:android:f635416f757a2cdbf23ed3',
    messagingSenderId: '861165103786',
    projectId: 'ballaghny-aleslam',
    storageBucket: 'ballaghny-aleslam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAatn4YuY97HEDX7StJdjJDWo_e5dkQQaY',
    appId: '1:861165103786:ios:afb730b598194f24f23ed3',
    messagingSenderId: '861165103786',
    projectId: 'ballaghny-aleslam',
    storageBucket: 'ballaghny-aleslam.firebasestorage.app',
    iosBundleId: 'com.badeea.BalligniALIslam',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi4Xb8QErhso9wRNPYTDEEy_C1z3MaDc8',
    appId: '1:861165103786:web:38906bb55ecd3d93f23ed3',
    messagingSenderId: '861165103786',
    projectId: 'ballaghny-aleslam',
    authDomain: 'ballaghny-aleslam.firebaseapp.com',
    storageBucket: 'ballaghny-aleslam.firebasestorage.app',
    measurementId: 'G-ZJXVKE2N5R',
  );

}